### ISSUE TITLE
Exchange assets Query limit off 250 records

### ISSUE THREAD

**Issue by ulfbicker** [mulesoft-catalyst/metrics-toolkit#109]
The exchange graphQL query is limited to 250 records. Which gives larger accounts wrong data, as the result set will be only 250. Could we run multiple queries for the different types of exchange assets?

**Comment by damiancalabresi** [comment]
I'll look at this and verify its feasibility

**Comment by mulepereira** [comment]
Could we resort to some pagination option?
Or instead revert to /exchange/api/v1/assets? It seems to have a larger limit accordingly to /properties/app-common.yaml:

```
exchange:
        assets:
          path: "/exchange/api/v1/assets"
          limit: "1000"
        graphql:
          path: "/graph/api/v2/graphql/"
          limit: "250"
```
